version: "3.5"

services:
  handle_server:
    image: openbookpublishers/handle_server
    container_name: "handle_server"
    restart: always
    volumes:
      - config:/hs
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 2461:2461

  handle_db:
    image: openbookpublishers/handle_db
    container_name: "handle_db"
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./config/db.env

volumes:
  config:
  db:
